version: '3.5'

services:

  db:
    container_name: postgres_test_commerce
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: testcommerece
      POSTGRES_USER: test_wsd
      POSTGRES_PASSWORD: test_wsd
    ports:
      - 5433:5432