spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testcommerce
    username: test_wsd
    password: test_wsd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

springdoc:
  swagger-ui:
    path: /v3/swagger-ui
    urls-primary-name: one
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true