spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testcommerce
    username: test_wsd
    password: test_wsd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none