spring:
  profiles.active: dev
  application.name: @project.artifactId@

server:
  servlet:
    context-path: /@project.artifactId@
  port: 8089
logging:
  file:
    path: /opt/tomcat/logs


management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-details: always